### ISSUE TITLE
怎么解决文件句柄的限制为1024 ？

### ISSUE THREAD

**Issue by fadeway32** [cocodx/Java-doc#5]

**Comment by cocodx** [comment]
/proc/sys/fs/file-max 
该文件指定了可以分配的文件句柄的最大数目

修改此硬限制的方法是修改/etc/rc.local脚本，在脚本中添加如下行：
echo 22158 > /proc/sys/fs/file-max
这是让Linux在启动完成后强行将系统级打开文件数硬限制设置为22158。修改完后保存此文件。
